### ISSUE TITLE
gatsby dependencies fail to install when using "next" in package.json

### ISSUE THREAD

**Issue by villeodell** [dabit3/gatsby-auth-starter-aws-amplify#17]
next tag is longer supported by gatsby
https://github.com/gatsbyjs/gatsby/issues/12463#issuecomment-471373639

**Comment by timhibberd** [comment]
Update the package.json file to use the latest Gatsby / plug-in versions rather than the deprecated "next" dist-tag.

**Comment by dabit3** [comment]
Updated this and this should be gtg now, thanks for the issue!
