### ISSUE TITLE
Browser refresh causes auth errors

### ISSUE THREAD

**Issue by ghost** [dabit3/gatsby-auth-starter-aws-amplify#18]
Just cloned this and tested it out. Seems to work fine but when I click refresh after logging in I get the following error:

[ERROR] 26:36.281 AuthClass - Cannot get the current user because the user pool is missing. Please make sure the Auth module is configured with a valid Cognito User Pool ID
e._log @ ConsoleLogger.js:80
e.error @ ConsoleLogger.js:146
(anonymous) @ Auth.js:1085
(anonymous) @ Auth.js:44
(anonymous) @ Auth.js:25
s @ Auth.js:17
Promise.then (async)
u @ Auth.js:18
a @ Auth.js:16
Promise.then (async)
u @ Auth.js:18
(anonymous) @ Auth.js:19
r @ Auth.js:15
e.currentAuthenticatedUser @ Auth.js:1043
a @ gatsby-browser.js:13
(anonymous) @ api-runner-browser.js:29
t.apiRunner @ api-runner-browser.js:20
E @ navigation.js:45
n.componentDidMount @ navigation.js:137
Ha @ react-dom.production.min.js:216
za @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Rs @ react-dom.production.min.js:250
Is @ react-dom.production.min.js:249
Ps @ react-dom.production.min.js:248
Cs @ react-dom.production.min.js:245
Qa @ react-dom.production.min.js:243
Ls @ react-dom.production.min.js:253
js @ react-dom.production.min.js:253
Bs.render @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:264
Ds @ react-dom.production.min.js:251
Ws @ react-dom.production.min.js:264
hydrate @ react-dom.production.min.js:266
(anonymous) @ production-app.js:113
setTimeout (async)
(anonymous) @ ready.js:32
(anonymous) @ production-app.js:112
Promise.then (async)
(anonymous) @ production-app.js:85
Promise.then (async)
(anonymous) @ production-app.js:31
s @ bootstrap:88
n @ bootstrap:45
t @ bootstrap:32
(anonymous) @ app-369a707a093d910ed867.js:1

**Comment by dabit3** [comment]
Thanks! I've updated versions and this seems to be fixed.
