### ISSUE TITLE
Security vulnerability: sensitive user fields in local storage

### ISSUE THREAD

**Issue by multidis** [dabit3/gatsby-auth-starter-aws-amplify#22]
Following user authentication, the user information returned from `Auth.currentAuthenticatedUser()` is saved to local storage:
https://github.com/dabit3/gatsby-auth-starter-aws-amplify/blob/master/src/components/Login.js#L25
https://github.com/dabit3/gatsby-auth-starter-aws-amplify/blob/master/src/utils/auth.js#L3

This appears to results in sensitive user fields such as the password being saved in local storage in plain text. Seems to be a serious security issue for anyone using this Gatsby starter.

Any suggestions on fixing that while still having a proper token of logged in user available for signing GraphQL calls etc.?

**Comment by dabit3** [comment]
Hi @multidis , I have tried to reproduce this issue but have not had any luck. Can you point me to how you were able to get the password saved to local storage?

Thanks for the issue.

**Comment by multidis** [comment]
I was re-evaluating this and indeed do not see the password anymore. Can not reproduce exactly where I have seen it in the past with the up-to-date amplify/gatsby versions, so considering this close. Sorry for the noise.

**Comment by dabit3** [comment]
Hey, no worries. I appreciate any issues. Thanks!
