### ISSUE TITLE
Incompatible graphql versions between Gatsby and Amplify

### ISSUE THREAD

**Issue by karldanninger** [dabit3/gatsby-auth-starter-aws-amplify#4]
I cloned this repo and followed the steps. I get the following error when I run `gatsby develop`

I investigated the package-lock file and noticed that Amplify deps for graphql are `0.13.0` and the Gatsby version is `0.13.2` I'm not sure why.  I'm assuming because the dependancy in your `package.json` is using `next` in a couple places and the versions got out of sync at some point.

```
error Cannot use GraphQLObjectType "SitePageConnection" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.


  Error: Cannot use GraphQLObjectType "SitePageConnection" from another module or realm.
  Ensure that there is only one instance of "graphql" in the node_modules
  directory. If different versions of "graphql" are the dependencies of other
  relied on modules, use "resolutions" to ensure only one version is installed.
  https://yarnpkg.com/en/docs/selective-version-resolutions
  Duplicate "graphql" modules cannot be used at the same time since different
  versions may have different capabilities and behavior. The data from one
  version used in the function from another could produce confusing and
  spurious results.
```

**Comment by fwahlqvist** [comment]
@karldanninger, did you manage to work out what dependency that need to be looked down?

**Comment by karldanninger** [comment]
Hey @fwahlqvist this thread helped https://github.com/gatsbyjs/gatsby/issues/8238#issuecomment-422285937 to ensure one version of graphql. For me, npm just didn’t work. We blew away node_modules and ended up using yarn for everything moving forward.

**Comment by fwahlqvist** [comment]
Thanks @karldanninger

**Comment by shawnmmatthews** [comment]
Just confirming you ended up going with 0.13.0 for Amplify compatibility correct? 0.13.2 doesn't seem to be an option.

**Comment by timhibberd** [comment]
Let the graphql dependencies sort themselves out by removing the following from the package.json file:

```
  "resolutions": {
    "graphql": "0.13.0"
  }
```

**Comment by dabit3** [comment]
Thanks for the issue, this has been updated and now should be gtg.
